#!/usr/bin/env zsh

# General Aliases
alias ls="ls --color=auto"

# Short names for tools
alias tf=tofu
alias cz=chezmoi

# Shortcuts for common commands
alias cze="EDITOR=~/.chezmoi_editor chezmoi edit"

# Little tiny oneliner "scripts" that take no args
# If I wanted to take args or be more complex, I'd use `make-script`.
alias cfr="curl -X POST https://celebrimbor.galaxy.casa/hooks/$CELEBRIMBOR_API_KEY/assets/full-rebuild"
alias mm="git fetch --all && git merge origin/main"
